# Generated by Django 4.1.3 on 2022-11-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
